import pathlib

import numpy as np

# same problem -> data-folder mapping as 03_train_gnn.py, so this reads
# directly from data generated by 01_generate_instances.py / 02_generate_dataset.py
# without duplicating it.
PROBLEM_FOLDERS = {
    'setcover': 'setcover/500r_1000c_0.05d',
    'cauctions': 'cauctions/100_500',
    'facilities': 'facilities/100_100_5',
    'indset': 'indset/500_4',
    'mknapsack': 'mknapsack/100_6',
}


class TaskSampler:
    """
    Samples MAML (support, query) file splits across MILP problem domains.
    Each problem domain (setcover, cauctions, ...) is one MAML task tau_i;
    each sample_*.pkl file inside it is a datapoint (G_k, y_k).
    """

    def __init__(self, data_root, problems, split, k_support, k_query, seed=0):
        self.k_support = k_support
        self.k_query = k_query
        self.rng = np.random.RandomState(seed)

        self.task_files = {}
        for problem in problems:
            folder = pathlib.Path(data_root) / PROBLEM_FOLDERS[problem] / split
            files = sorted(str(f) for f in folder.glob('sample_*.pkl'))
            if len(files) < k_support + k_query:
                raise ValueError(
                    f"task '{problem}' only has {len(files)} samples in {folder}, "
                    f"need at least k_support + k_query = {k_support + k_query}")
            self.task_files[problem] = files

        self.problems = list(self.task_files.keys())

    def sample_task(self, problem=None):
        """Draws one task: a (support_files, query_files) split for one problem domain."""
        if problem is None:
            problem = self.problems[self.rng.randint(len(self.problems))]

        files = self.rng.choice(self.task_files[problem], self.k_support + self.k_query, replace=False)
        support_files = files[:self.k_support].tolist()
        query_files = files[self.k_support:].tolist()
        return problem, support_files, query_files

    def sample_meta_batch(self, meta_batch_size):
        """Draws several tasks at once, i.e. one MAML meta-batch."""
        return [self.sample_task() for _ in range(meta_batch_size)]
